[settings]
    [settings.tag_colors]
    personal = "dcbe8a"
    tech = "8acfce"
    art = "dd9ace"

    [settings.fields]
    date_upd = "[upd {}]"
    links = '<a href="{value}">{key}</a>'


[posts]
    [posts.journey_fanart]
    title = "Journey Fanart"
    filename = "mar23_journey"
    visible = true
    tags = [ "art" ]
    links = { ".kra (250MB lol)" = "/resources/art/journey/journey.kra", "cutout video" = "/resources/art/journey/cutout.mp4" }
    date = "30.03.2023"
    # date_upd = "30.04.2023"

    [posts.complexity_in_art]
    title = "Complexity in art"
    filename = "22_07_17_abstract_pixel_art"
    visible = false
    tags = [ "art", "personal" ]
    links = []
    date = "20.07.2022"
    # date_upd = ""

    [posts.speech_diary_scripts]
    title = "Speech to text diary scripts"
    filename = "mar2022_phonediary"
    visible = true
    tags = [ "tech", "linux" ]
    links = { "GH Repo"="https://github.com/TeaWhyDee/public-scripts/tree/master/phone_diary", "SpeechRec Docs"="https://pypi.org/project/SpeechRecognition/" }
    date = "10.04.2022"

    [posts.mpvsplice]
    title = "Simple video editing with MPV"
    filename = "mar22_mpvsplice"
    visible = true
    tags = [ "tech", "linux" ]
    links = { "mpv-splice repo"="https://github.com/TeaWhyDee/mpv-yt-splice", "public-scripts(includes 8mb)"="https://github.com/TeaWhyDee/public-scripts" }
    date = "13.03.2022"

    [posts.hld_music]
    title = "Hyper Light Drifters magnificent sound "
    filename = "hld"
    visible = true
    tags = [ "personal", "media" ]
    links = { "mpv-splice repo"="https://github.com/TeaWhyDee/mpv-yt-splice", "public-scripts(includes 8mb)"="https://github.com/TeaWhyDee/public-scripts" }
    date = "06.03.2022"

    [posts.music_players]
    title = "Music Playing: Local & Remote"
    filename = "music_playing"
    visible = true
    tags = [ "tech", "linux" ]
    links = { "mpv-splice repo"="https://github.com/TeaWhyDee/public-dotfiles" }
    date = "20.02.2022"

    [posts.updating_the_website]
    title = "Updating the Website"
    filename = "feb22_website"
    visible = true
    tags = [ "tech" ]
    links = { "GitHub Repo" = "https://github.com/TeaWhyDee/teawd-site-generator" }
    date = "06.02.2022"

    [posts.weird_grid_ui]
    title = "Small GUI to Make Weird Designs"
    filename = "weird_grid_ui"
    visible = true
    tags = [ "tech", "art" ]
    links = { "GitHub Repo"="https://github.com/TeaWhyDee/angled-grid-draw" }
    date = "30.01.2022"
    date_upd = "06.02.2022"

    [posts.weekly_posts]
    title = "Weekly Blog Posts"
    filename = "weekly_posts"
    visible = true
    tags = [ "personal" ]
    links = { "Original size pixel art"="/resources/art/work_day_pixel_art/work_day_pixel_art_pixel.png" }
    date = "23.01.2022"

    [posts.art_challenge_1]
    title = "15 Day Challenge: Drawing"
    filename = "art_challenge_1"
    visible = true
    tags = [ "art", "personal" ]
    links = { "Drawings (24M)" = "/resources/ArtChal1/AC_Jul2021_pictures.zip" }
    date = "31.07.2021"

    [posts.website_artwork]
    title = "Website Artwork"
    filename = "website_artwork"
    visible = true
    tags = [ "art" ]
    links = { ".svg files (113K)" = "/resources/website_content.zip", "Inkscape.org"="https://inkscape.org/" }
    date = "26.07.2021"

